In [1]:
import pandas as pd
import spacy
from tqdm import tqdm
from spacy.matcher import PhraseMatcher

In [2]:
csv_file = 'preprocessed_0f_mexico.csv'

In [3]:
df = pd.read_csv(csv_file)

In [4]:
df

,text,date,category,processed_text
0,RT @FCBarcelona: Our solidarity with the victi...,20_9_2017,not_humanitarian,rt our solidarity with the victims of the eart...
1,Mexico earthquake: Many children killed at pri...,20_9_2017,injured_or_dead_people,mexico earthquake many children killed at prim...
2,Obamaâ€™s Response To The Earthquake In #Mexic...,20_9_2017,not_humanitarian,obamaâ response to the earthquake in mexicocit...
3,RT @AmichaiStein1: #BREAKING: Israel search &a...,20_9_2017,rescue_volunteering_or_donation_effort,rt breaking israel search amp rescue mission h...
4,RT @AmichaiStein1: #BREAKING: Israel search &a...,20_9_2017,rescue_volunteering_or_donation_effort,rt breaking israel search amp rescue mission h...
...,...,...,...,...
1375,Carlos santana donates $100k to mexico earthqu...,06_10_2017,rescue_volunteering_or_donation_effort,carlos santana donates to mexico earthquake re...
1376,Seth troxler donates 10k to earthquake relief ...,06_10_2017,rescue_volunteering_or_donation_effort,seth troxler donates to earthquake relief effo...
1377,Entercom/San Francisco Stations Raise Funds Fo...,06_10_2017,rescue_volunteering_or_donation_effort,entercom san francisco stations raise funds fo...
1378,Mexico Earthquakes | International Medical Cor...,06_10_2017,other_relevant_information,mexico earthquakes international medical corps
1379,Napa school employee Valentin Fuentes Villanue...,06_10_2017,injured_or_dead_people,napa school employee valentin fuentes villanue...

In [5]:
def extract_locations(text):
    nlp = spacy.load("en_core_web_sm")
    matcher = PhraseMatcher(nlp.vocab)
    # Add custom location names to the matcher
    location_patterns = []
    for loc in location_patterns:
        matcher.add("LOCATION", None, nlp(loc))

    doc = nlp(text)
    locations = []
    
    # Extract locations using NER
    for ent in doc.ents:
        if ent.label_ == 'GPE' or ent.label_ == 'LOC':
            locations.append(ent.text)

    # Extract additional locations using the custom matcher
    matches = matcher(doc)
    for match_id, start, end in matches:
        span = doc[start:end]
        locations.append(span.text)
    
    return locations

In [6]:
all_locations1 = []
flags=[]
for text in tqdm(df['processed_text'], desc="Extracting Locations", total=len(df)):
    locations = extract_locations(text)
    all_locations1.extend(locations)
    
    # Set the flag to 1 if locations were found, otherwise 0
    if locations:
        flags.append(1)
    else:
        flags.append(0)

# Add the flag column to the DataFrame
df['flag1'] = flags
# Print or use the list of all locations
print(all_locations1)

Extracting Locations:   0%|          | 0/1380 [00:00<?, ?it/s]C:\Users\deepp\AppData\Roaming\Python\Python312\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\deepp\AppData\Roaming\Python\Python312\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Extracting Locations: 100%|██████████| 1380/1380 [11:34<00:00,  1.99it/s]

['mexico', 'mexico', 'israel', 'mexico', 'israel', 'mexico', 'israel', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexicoâ city', 'rt mexico city airport', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'rt mexico', 'mexico', 'mexico', 'aá¼ÿ', 'mexico', 'mexico', 'mexico', 'mexico', 'new zealand', 'mexico city', 'mexico city', 'rt mexico', 'central mexico', 'central mexico', 'central mexico', 'central mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'dona', 'mexico city', 'rt mexico city', 'rt mexico city', 'rt mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'jj_worldtour mexico', 'mexico', 'jj_worldtour mexico', 'mexico', 'jj_worldtour mexico', 'mexico', 'jj_worldtour mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'jojutla mexico', 'mexico city', 'mexico', 'mexico city', 'mexico city', 'rt mexico city', 'mexico', 'mexico city', 'mexico city', 'central mexico', 'mexicoâ', 'mexico', 'mexico', 'mexico city', 'beyoncã', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'canada', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico city', 'magdalena', 'emsr', 'central mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'india', 'kerala', 'central mexico', 'mexico', 'mexico city', 'mexico', 'central mexico', 'mexico city', 'mexico city', 'mexico city', 'central mexico', 'mexico city', 'mexico', 'mexico', 'xicoestã', 'mexico', 'mexico', 'mexico city', 'central mexico', 'mexico city', 'mexico', 'mexico city', 'mexico moment earthquake', 'caribbean', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'central mexico', 'mexico city', 'mexico', 'mexico', 'rt mexico', 'mexico', 'mexico', 'mexicoâ', 'rt mexico', 'mexico', 'mexicoâ', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico justiceorelse', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'california', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mo', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'central mexico', 'mexico city', 'mexico', 'newsela', 'mexico', 'newsela', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexicoâ', 'mexico city', 'chiapas', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'japan', 'mexico', 'mexico', 'kuwait', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'rt mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city school', 'mexico', 'mexico city', 'mexico', 'photos mexico', 'mexico', 'california', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'guatemala', 'mexico', 'venezuela', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'de mexico mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'rabosco mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'south bay', 'mexico', 'mexico', 'mexico', 'mexico', 'kprc', 'mexico', 'california', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'rt mexico', 'mexico', 'boston', 'mexico', 'mexico', 'mexico', 'central mexico', 'mexico', 'mexico', 'mexico', 'salma', 'mexico', 'mexico', 'central mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico city', 'costa rica', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'algeria', 'mexico', 'mexico', 'mexico city', 'mexico', 'taiwan', 'mexico', 'taiwan', 'mexico', 'mexico', 'mexico', 'kenan', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'boston', 'mexicoâ', 'mexico', 'mexico', 'mexico', 'mexico city', 'las vegas', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'denver', 'mexico city', 'mexico', 'mexico city', 'china', 'mexico', 'central mexico', 'mexico', 'mexico city', 'mexico', 'mexicoâ', 'central mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico', 'salma', 'mexico', 'mexicoâ', 'israel', 'mexico', 'mexico', 'milwaukee', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'juchitan', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'notch mexico', 'mexico', 'benito', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'forex mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'japan', 'mexico', 'calgary', 'mexico', 'mexico', 'mexico', 'mexico', 'gistmania', 'mexico', 'mexico', 'mexico', 'mexico city puebla', 'mexico', 'los angeles times', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'central mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'seattle', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'noma', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'northern ireland', 'mexico', 'mexico city', 'mexico', 'mexico', 'arizona', 'mexico city', 'mexico', 'mexico city', 'denver', 'mexico', 'denver', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'britain', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'san antonio', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'the united kingdom elizabeth ii', 'mexico', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mobilizes', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'japan', 'mexico', 'japan', 'mexico', 'japan', 'mexico', 'japan', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'southern mexico', 'mexico', 'mexico', 'oaxaca mexico', 'mexico', 'california', 'mexico city', 'mexico', 'mexicoâ', 'mexico', 'mexico city', 'oaxaca mexico', 'mexico', 'mexico city', 'frida', 'mexico city', 'oaxaca mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'salina cruz', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'southern mexico', 'mexico', 'rt mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'california', 'mexico', 'frida', 'mexico city', 'mexico', 'the united states', 'mexico', 'new mexico', 'rt mexico', 'mexico city', 'mexico', 'denver', 'mexico', 'mexico', 'salma', 'salma', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'oaxaca', 'mexico', 'mexico', 'mexico', 'california', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'iran', 'ottawa', 'mexico', 'ottawa', 'mexico', 'mexico', 'rt mexico', 'healthnews', 'mexico city', 'mexico', 'mexico', 'mexico city', 'japan', 'israel', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'jojutla mexico', 'mexico city', 'uk', 'mexico', 'xico', 'mexico city', 'mexico', 'frida', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'coin mexico', 'north korea brexit', 'mexico', 'mexico city', 'the united states', 'mexico', 'xico', 'paredon mexico', 'mexico', 'á¼žfá¼ÿ', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'central mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexicoâ', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexicoâ', 'mexico', 'mexico', 'paredon mexico', 'venezuela', 'mexico', 'buhari', 'unga', 'mexico', 'oaxaca mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'west coast', 'mexico', 'oaxaca mexico', 'mexico', 'mexico', 'london', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'israel', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'toronto', 'mexico', 'west new york', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'los angeles', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'central mexico', 'mexico city', 'napalovesmexico', 'mexico', 'mexico', 'mexico', 'arizona', 'mexico', 'texas', 'florida', 'los angeles', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'israel', 'mexico', 'israel', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'sniffer doggos', 'mexico', 'mexico', 'las vegas', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'venezuela', 'mexico', 'san francisco', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'houston', 'florida', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'taiwan', 'us', 'mexico', 'taiwan', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'oaxaca', 'calgary', 'mexico city', 'mexico', 'los topos', 'central mexico', 'mexico', 'fuerza mexico', 'mexico', 'mexico city', 'russia', 'mexico', 'mexico city', 'mexicoâ', 'mexico city', 'mexico', 'myanmar', 'mexico', 'myanmar', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'miami', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'north korea', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'japan', 'mexico', 'kompany', 'mexico', 'washington', 'california', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'rt mexico', 'mexico', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'israel', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'frida', 'mexico', 'russia', 'latin america', 'mexico', 'mexico', 'mexicoâ', 'deafâ', 'mexico city', 'mexico', 'ottawa', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'taiwan', 'mexico', 'taiwan', 'mexico', 'taiwan', 'mexico', 'mexico', 'mexico city', 'mexico city', 'oaxaca mexico', 'mexico', 'mexico city', 'springfield', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'rt mexico', 'mexico', 'north korea', 'mexico', 'mexico', 'north korea', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexicoâ', 'mexico city', 'florida', 'florida', 'mexico city', 'mexico', 'houston', 'mexico city', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'la', 'mexico', 'mexico', 'mexico', 'mexico', 'vogue mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'wasn mexico city', 'tres', 'houston', 'mexico', 'tres', 'mexico', 'bronx', 'mexico', 'mexico', 'mexico', 'north pacific', 'mexico', 'south mexico', 'mexico', 'mexico', 'mexicoâ', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'vogue mexico', 'mexico city', 'recent mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'mexico', 'california', 'vogue mexico', 'mexico city', 'mexico', 'mexico city', 'mexico city', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'shot mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'calgary', 'colonia', 'mexico', 'california', 'california', 'california', 'california', 'mexico', 'kankakee', 'mexico city', 'mexico city', 'mexico', 'london', 'mexico', 'oaxaca', 'mexico', 'mexico', 'mexicoâ', 'mexico', 'mexico', 'mexicoâ city', 'mexicoâ city', 'mexico city', 'mexico', 'oaxaca', 'frida', 'mexico', 'mexico', 'cuba', 'mexico', 'mexico city', 'sacramento', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'america', 'scary mexico', 'mexico', 'jojutla', 'mexico', 'frida', 'mexico', 'mexico', 'mexico city', 'mexico', 'mexico', 'oaxaca', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico city', 'mexico city', 'mexico city', 'mexico city', 'mexico', 'adams county', 'mexico', 'mexico', 'mexico', 'mexico', 'mexico', 'san francisco', 'mexico', 'mexico', 'mexico']

In [9]:
df

,text,date,category,processed_text,flag1
0,RT @FCBarcelona: Our solidarity with the victi...,20_9_2017,not_humanitarian,rt our solidarity with the victims of the eart...,1
1,Mexico earthquake: Many children killed at pri...,20_9_2017,injured_or_dead_people,mexico earthquake many children killed at prim...,1
2,Obamaâ€™s Response To The Earthquake In #Mexic...,20_9_2017,not_humanitarian,obamaâ response to the earthquake in mexicocit...,0
3,RT @AmichaiStein1: #BREAKING: Israel search &a...,20_9_2017,rescue_volunteering_or_donation_effort,rt breaking israel search amp rescue mission h...,1
4,RT @AmichaiStein1: #BREAKING: Israel search &a...,20_9_2017,rescue_volunteering_or_donation_effort,rt breaking israel search amp rescue mission h...,1
...,...,...,...,...,...
1375,Carlos santana donates $100k to mexico earthqu...,06_10_2017,rescue_volunteering_or_donation_effort,carlos santana donates to mexico earthquake re...,1
1376,Seth troxler donates 10k to earthquake relief ...,06_10_2017,rescue_volunteering_or_donation_effort,seth troxler donates to earthquake relief effo...,1
1377,Entercom/San Francisco Stations Raise Funds Fo...,06_10_2017,rescue_volunteering_or_donation_effort,entercom san francisco stations raise funds fo...,1
1378,Mexico Earthquakes | International Medical Cor...,06_10_2017,other_relevant_information,mexico earthquakes international medical corps,1
1379,Napa school employee Valentin Fuentes Villanue...,06_10_2017,injured_or_dead_people,napa school employee valentin fuentes villanue...,1

In [10]:
count_ones = df['flag1'].sum()

In [11]:
count_ones

1094

In [7]:
locations_df = pd.DataFrame(all_locations1, columns=['Location'])

In [8]:
locations_df

           Location
0            mexico
1            mexico
2            israel
3            mexico
4            israel
...             ...
1233         mexico
1234  san francisco
1235         mexico
1236         mexico
1237         mexico

[1238 rows x 1 columns]

In [10]:
locations_df.to_csv('extracted_locations_mexico.csv', index=False)

In [11]:
from geopy.geocoders import Nominatim

In [12]:
def get_coordinates(location):
    geolocator = Nominatim(user_agent="location_finder")
    try:
        location_info = geolocator.geocode(location)
        if location_info:
            return location_info.latitude, location_info.longitude
        else:
            return None, None
    except:
        return None, None

In [13]:
locations_data = []

In [14]:
unique_locations = set(all_locations)
for location in tqdm(unique_locations, desc="Geocoding Locations"):
    frequency = all_locations.count(location)
    latitude, longitude = get_coordinates(location)
    if latitude is not None and longitude is not None:
        locations_data.append({'Location': location, 'Frequency': frequency, 'Latitude': latitude, 'Longitude': longitude})

Geocoding Locations: 100%|███████████████████████████████████████████████████████████| 122/122 [02:26<00:00,  1.20s/it]

In [15]:
coordinate_mexico = pd.DataFrame(locations_data)

In [16]:
coordinate_mexico

              Location  Frequency   Latitude   Longitude
0            las vegas          2  36.167256 -115.148516
1               ottawa          3  45.420878  -75.690111
2                 aá¼ÿ          1  17.909500   38.336900
3          springfield          1  39.799017  -89.643957
4   mexico city puebla          1  19.407205  -99.082468
..                 ...        ...        ...         ...
92               deafâ          1  52.748620   -8.029006
93             chiapas          1  16.500000  -92.500000
94          california         12  36.701463 -118.755997
95            kankakee          1  41.125390  -87.848682
96    de mexico mexico          1  19.432630  -99.133178

[97 rows x 4 columns]

In [17]:
coordinate_mexico.to_csv('coordinates_mexico.csv', index=False)